[package]
name = "mdbook-pandoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = "4.3.23"
mdbook = "0.4.34"
semver = { versio = "1.0.18", features = ["serde"] }
serde = "1.0.183"
serde_json = "1.0.105"
