[package]
name = "mdbook-citeproc"
version = "0.0.7"
edition = "2021"

[dependencies]
anyhow = "1"
clap = "4"
mdbook = "0.4"
pulldown-cmark = "0.10"
semver = { version = "1", features = ["serde"] }
serde = "1"
serde_json = "1"
