[package]
name = "mdbook-citeproc"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "4"
mdbook = "0.4"
pulldown-cmark = "0.10"
semver = { version = "1", features = ["serde"] }
serde = "1"
serde_json = "1"
